
@extends('layouts.default')
@section('content')
<section id="content">
         <!-- BEGIN: Content-->
    <div class="app-content content">
      <div class="content-overlay"></div>
      <div class="header-navbar-shadow"></div>
      <div class="content-wrapper">
          <div class="content-header row">

          </div>
          <div class="content-body">
              <!-- users edit start -->



              <section class="users-edit">
                  <div class="card">
                      <div class="card-content">
                          <div class="card-body">
                              <ul class="nav nav-tabs mb-3" role="tablist">
                                  <li class="nav-item">
                                      <a class="nav-link d-flex align-items-center active" id="account-tab" data-toggle="tab" href="#account" aria-controls="account" role="tab" aria-selected="true">
                                          <i class="feather icon-user mr-25"></i><span class="d-none d-sm-block">Pending Debits </span> &nbsp;&nbsp; <span class="badge badge badge-pill badge-danger float-right mr-2"> {{ $bills->total() }}  </span>
                                      </a>
                                  </li>

                                    <!-- Inputs Group with Buttons -->

                                  <div class="col-md-6 col-12 mb-1">
                                    <form action="/find-invoice" method="GET">
                                      <fieldset>
                                          <div class="input-group">

                                              <input type="text" class="form-control" id="search by name , id , visit type ..." name="search" placeholder="search...">


                                              &nbsp;&nbsp;&nbsp;&nbsp;

                                              <input type="text" name='review_period' id='review_period' class="input-sm form-control round" placeholder="Search by reservation, name, invoice number..">
                                              <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" type="button"><i class="feather icon-search"></i></button>
                                              </div>
                                          </div>

                                      </fieldset>

                                    </form>
                                  </div>
                              </ul>


                              <div class="tab-content">
                                  <div class="tab-pane active" id="account" aria-labelledby="account-tab" role="tabpanel">
                                      <!-- users edit media object start -->
                                      <div class="row" id="table-hover-animation">
                                        <div class="col-12">
                                            <div class="card">

                                              <div class="alert alert-primary mt-1 p-1">
                                                <div class="col-12 d-flex flex-sm-row flex-column justify-content-end">
                                                </div>
                                              </div>

                                                <div class="card-content">
                                                    <div class="card-body">

                                                        <div class="table-responsive">

                                                            <table id="bills" class="table table-hover-animation table-striped mb-0 font-small-2 text-center">
                                                                <thead>


                                                                    <tr>
                                                                      <th scope="col">Debit #</th>
                                                                      <th scope="col">Reference</th>
                                                                      <th scope="col">Customer</th>
                                                                      <th scope="col">Item</th>
                                                                      <th scope="col">Date</th>
                                                                      <th scope="col">Currency</th>
                                                                      <th scope="col">Amount</th>
                                                                      <th scope="col">Status</th>
                                                                      <th scope="col">Generated By</th>
                                                                      <th scope="col"></th>
                                                                      <th scope="col"></th>

                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                  @foreach( $bills->groupby('invoice_number') as $bill )
                                                                  <tr>

                                                                    @foreach($bill as $item)
                                                                    <td>{{ $item->invoice_number }}</td>
                                                                    <td>{{ $item->reference }}</td>
                                                                    <td>{{Str::limit($item->fullname,20)}}</td>
                                                                    <td>{{$item->product}}</td>
                                                                    <td>{{ $item->invoice_date }}</td>
                                                                    <td>{{ $item->currency }}</td>
                                                                    <td>{{ number_format($item->amount , 2, '.', ',')}}</td>

                                                                    <td>{{ $item->payment_status }}</td>
                                                                    <td>{{ $item->created_by }}</td>

									                                
                                                                    <td>
                                                                        @permission('collect-payment')
                                                                      @if($item->payment_status != 'Paid')
                                                                      <a href="/make-payment/{{ $item->id }}" class="btn mr-1 mb-1 btn-danger btn-sm">Collect Payment</a>
                                                                      @else
                                                                      <a href="#" class="btn mr-1 mb-1 btn-success btn-sm">Paid</a>
                                                                      @endif
                                                                      @endpermission
                                                                    </td>
                                                                   

                                                                    <td class="product-action">
                                                                      <a href="/print-invoice/{{ $item->id }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Print Debit"><i class="fa fa-print"></i></a>
                                                                    </td>
                                                                    

                                                                  </tr>
                                                                  @endforeach
                                                                  <tr>
                                                                    <td colspan="10" class="text-right no-border"><strong>Debit Total</strong></td>
                                                                    <td> <strong>{{ number_format($bill->sum('amount'), 2, '.', ',') }} </strong></td>
                                                                  </tr>
                                                                  @endforeach

                                                                  
                                                                </tbody>
                                                            </table>

                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                      <div class="col-sm-12 col-md-5">
                                      <div> Record(s) Found : <img src="/images/250500.svg" width="30px" height="30px"> {{ $bills->total() }} {{ Str::plural('Debit', $bills->total()) }}</div>
                                    </div>
                                      <div class="col-sm-12 col-md-7">
                                        {!!$bills->render()!!}
                                      </div>
                                        </div>
                                      <!-- users edit media object ends -->
                                      <!-- users edit account form start -->

                                  </div>

                              </div>
                          </div>
                      </div>
                  </div>
              </section>
              <!-- users edit ends -->

          </div>
      </div>
  </div>
  <!-- END: Content-->

  <div class="sidenav-overlay"></div>
  <div class="drag-target"></div>

@stop


<style type="text/css">
    .product-action > a {
        margin: 0 5px;
    }
</style>

<script src="{{ asset('/event_components/jquery.min.js')}}"></script>



<script type="text/javascript">
$(function() {

    var start = moment().subtract(29, 'days');
    var end = moment();

    function cb(start, end) {
        $('#review_period span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }

    $('#review_period').daterangepicker({
        startDate: start,
        endDate: end,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

    cb(start, end);

});


</script>
